!!python/object:nerfstudio.engine.trainer.TrainerConfig
_target: !!python/name:nerfstudio.engine.trainer.Trainer ''
data: null
experiment_name: unnamed
gradient_accumulation_steps: {}
load_checkpoint: null
load_config: null
load_dir: null
load_scheduler: true
load_step: null
log_gradients: false
logging: !!python/object:nerfstudio.configs.base_config.LoggingConfig
  local_writer: !!python/object:nerfstudio.configs.base_config.LocalWriterConfig
    _target: !!python/name:nerfstudio.utils.writer.LocalWriter ''
    enable: true
    max_log_size: 10
    stats_to_track: !!python/tuple
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Iter (time)
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test PSNR
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Vis Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - ETA (time)
  max_buffer_size: 20
  profiler: basic
  relative_log_dir: !!python/object/apply:pathlib.PosixPath []
  steps_per_log: 10
machine: !!python/object:nerfstudio.configs.base_config.MachineConfig
  device_type: cuda
  dist_url: auto
  machine_rank: 0
  num_devices: 1
  num_machines: 1
  seed: 42
max_num_iterations: 100001
method_name: neus-facto
mixed_precision: true
optimizers:
  field_background:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: &id001 !!python/name:torch.optim.adam.Adam ''
      eps: 1.0e-15
      lr: 1.0e-04
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.CosineDecaySchedulerConfig
      _target: &id002 !!python/name:nerfstudio.engine.schedulers.CosineDecayScheduler ''
      learning_rate_alpha: 0.05
      max_steps: 100001
      warm_up_end: 500
  fields:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 5.0e-04
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.CosineDecaySchedulerConfig
      _target: *id002
      learning_rate_alpha: 0.05
      max_steps: 100001
      warm_up_end: 500
  proposal_networks:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 1.0e-02
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.MultiStepSchedulerConfig
      _target: !!python/name:nerfstudio.engine.schedulers.MultiStepScheduler ''
      gamma: 0.5
      max_steps: 100001
      milestones: !!python/tuple
      - 30000
      - 60000
      - 90000
output_dir: !!python/object/apply:pathlib.PosixPath
- outputs
pipeline: !!python/object:nerfstudio.pipelines.base_pipeline.VanillaPipelineConfig
  _target: !!python/name:nerfstudio.pipelines.base_pipeline.VanillaPipeline ''
  datamanager: !!python/object:nerfstudio.data.datamanagers.base_datamanager.VanillaDataManagerConfig
    _target: !!python/object/apply:_operator.getitem
    - !!python/name:nerfstudio.data.datamanagers.base_datamanager.VanillaDataManager ''
    - !!python/name:nerfstudio.data.datasets.neus_dataset.NeusDataset ''
    camera_optimizer: null
    camera_res_scale_factor: 1.0
    collate_fn: !!python/name:nerfstudio.data.utils.nerfstudio_collate.nerfstudio_collate ''
    data: null
    dataparser: !!python/object:nerfstudio.data.dataparsers.neus_dataparser.NeusDataParserConfig
      _target: !!python/name:nerfstudio.data.dataparsers.neus_dataparser.Neus ''
      auto_scale_poses: true
      center_method: none
      data: !!python/object/apply:pathlib.PosixPath
      - /
      - nerf-sessions
      - nerf_data_with_background
      depth_unit_scale_factor: 1.0
      downscale_factor: null
      eval_interval: 8
      eval_mode: fraction
      load_3D_points: false
      mask_color: null
      orientation_method: up
      scale_factor: 1.0
      scene_scale: 0.5
      train_split_fraction: 0.99999999
    eval_image_indices: !!python/tuple
    - 0
    eval_num_images_to_sample_from: -1
    eval_num_rays_per_batch: 2048
    eval_num_times_to_repeat_images: -1
    images_on_gpu: true
    masks_on_gpu: true
    patch_size: 1
    pixel_sampler: !!python/object:nerfstudio.data.pixel_samplers.PixelSamplerConfig
      _target: !!python/name:nerfstudio.data.pixel_samplers.PixelSampler ''
      fisheye_crop_radius: null
      ignore_mask: false
      is_equirectangular: false
      keep_full_image: false
      max_num_iterations: 10000
      num_rays_per_batch: 8192
      rejection_sample_mask: true
    train_num_images_to_sample_from: -1
    train_num_rays_per_batch: 4096
    train_num_times_to_repeat_images: -1
  model: !!python/object:nerfstudio.models.neus_facto.NeuSFactoModelConfig
    _target: !!python/name:nerfstudio.models.neus_facto.NeuSFactoModel ''
    background_color: white
    background_model: mlp
    base_variance: 64
    collider_params:
      far_plane: 2.0
      near_plane: 0.5
    eikonal_loss_mult: 0.1
    enable_collider: true
    eval_num_rays_per_chunk: 2048
    far_plane: 1
    far_plane_bg: 1000
    fg_mask_loss_mult: 0.01
    interlevel_loss_mult: 1.0
    loss_coefficients:
      rgb_loss_coarse: 1.0
      rgb_loss_fine: 1.0
    mono_depth_loss_mult: 1.0e-15
    mono_normal_loss_mult: 0.0
    near_plane: 0.5
    num_neus_samples_per_ray: 96
    num_proposal_iterations: 2
    num_proposal_samples_per_ray: !!python/tuple
    - 256
    - 96
    num_samples: 64
    num_samples_importance: 64
    num_samples_outside: 32
    num_up_sample_steps: 4
    overwrite_near_far_plane: false
    periodic_tvl_mult: 0.0
    perturb: true
    prompt: null
    proposal_net_args_list:
    - hidden_dim: 64
      log2_hashmap_size: 21
      max_res: 64
      num_levels: 5
    - hidden_dim: 64
      log2_hashmap_size: 21
      max_res: 256
      num_levels: 5
    proposal_update_every: 5
    proposal_warmup: 50
    proposal_weights_anneal_max_num_iters: 1000
    proposal_weights_anneal_slope: 10.0
    sdf_field: !!python/object:nerfstudio.fields.sdf_field.SDFFieldConfig
      _target: !!python/name:nerfstudio.fields.sdf_field.SDFField ''
      appearance_embedding_dim: 32
      base_res: 64
      beta_init: 0.1
      bias: 0.1
      divide_factor: 2.0
      encoding_type: hash
      features_per_level: 8
      geo_feat_dim: 256
      geometric_init: true
      hidden_dim: 256
      hidden_dim_color: 256
      inside_outside: false
      log2_hashmap_size: 21
      max_res: 2048
      num_layers: 2
      num_layers_color: 2
      num_levels: 16
      smoothstep: true
      use_appearance_embedding: false
      use_grid_feature: true
      use_hash: true
      weight_norm: false
    use_average_appearance_embedding: false
    use_proposal_weight_anneal: true
    use_same_proposal_network: false
    use_single_jitter: true
project_name: nerfstudio-project
prompt: null
relative_model_dir: !!python/object/apply:pathlib.PosixPath
- nerfstudio_models
save_only_latest_checkpoint: true
steps_per_eval_all_images: 1000000
steps_per_eval_batch: 5000
steps_per_eval_image: 5000
steps_per_save: 2000
use_grad_scaler: true
viewer: !!python/object:nerfstudio.configs.base_config.ViewerConfig
  camera_frustum_scale: 0.1
  default_composite_depth: true
  image_format: jpeg
  jpeg_quality: 75
  make_share_url: false
  max_num_display_images: 512
  num_rays_per_chunk: 32768
  quit_on_train_completion: false
  relative_log_filename: viewer_log_filename.txt
  websocket_host: 0.0.0.0
  websocket_port: null
  websocket_port_default: 7007
vis: viewer+tensorboard
