version: "3.8"

services:
  nerfstudio:
    shm_size: '12gb'
    image: nerfstudio:latest
    build:
      context: ..
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      DISPLAY: $DISPLAY
    ports:
      - "7007:7007"
    volumes:
      - ../:/workspace/
      - /tmp/.X11-unix:/tmp/.X11-unix
      # mount a docker volume to the container at /nerf-session and set the owner as 1000:1000
      - nerf-sessions:/nerf-sessions  # this is the volume that will be mounted to the container
    working_dir: /workspace/
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [ gpu ]

#make the volume if it doesn't exist
volumes:
  nerf-sessions:
    name: nerf-sessions
    external: true