name: Update Docker Compose Files

on: [push]

jobs:
  update-compose-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Find Docker Compose files
      run: |
        compose_files=$(find . -type f -name "docker-compose*.yml" -o -name "docker-compose*.yaml")
        echo "COMPOSE_FILES=$compose_files" >> $GITHUB_ENV
        
    - name: Update Docker Compose files
      run: |
        for file in ${{ env.COMPOSE_FILES }}; do
          if grep -q "nerf-sessions" "$file"; then
            sed -i 's/external: true/external: false/g' "$file"
            echo "Updated $file"
          fi
        done
        
    - name: Commit changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update Docker Compose files"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}